/**
 * Server-side Research Agent: a real LLM agent that pays, on-chain, for the
 * data sources it needs to answer a question.
 *
 * The agent is given a single `purchase_source` tool. Every call settles a REAL
 * Stellar payment through the published @reapp-sdk/core (MandateRegistry.execute_
 * payment). The mandate budget is enforced ON-CHAIN: once the agent has spent its
 * budget, the contract rejects further purchases and the agent must synthesise an
 * answer from what it could afford. The contract enforces the budget on-chain;
 * the SDK cannot exceed it.
 *
 * The LLM is reached through a provider-failover layer (see ./llm): if the
 * primary provider runs out of credit or is rate-limited, the call transparently
 * fails over to the backup so the agent never goes dark mid-run. If every
 * provider is exhausted, the agent emits a degraded report built directly from
 * the sources it already purchased on-chain.
 *
 * Runs only in the Node API route. Streams structured events via an async generator.
 */
import { reapp, type CreateIntentMandateInput } from "@reapp-sdk/core";
import { AllProvidersExhausted, buildFailoverLlm, type FailoverLlm, type LlmMessage, type LlmTool } from "./llm";
import { log } from "./log";

/** Price per source, in XLM. The mandate budget (see reapp-server.BUDGET = "3.00")
 *  covers three of these — the contract blocks the fourth. */
export const SOURCE_PRICE = "1.00";

export type Source = {
  id: string;
  name: string;
  icon: string;
  /** First-person persona used when a sub-agent role-plays this source's findings. */
  persona: string;
};

export const SOURCES: Source[] = [
  { id: "market", name: "Market Data API", icon: "📈", persona: "a real-time financial market-data provider — prices, volume, liquidity, volatility, and on-chain flows" },
  { id: "academic", name: "Academic Papers", icon: "📚", persona: "a peer-reviewed academic research index — empirical studies, citations, and methodology" },
  { id: "news", name: "News Archive", icon: "📰", persona: "a global news and press-release archive — recent events, announcements, and market sentiment" },
  { id: "patents", name: "Patent Database", icon: "⚗️", persona: "a worldwide patent and IP-filings database — inventions, assignees, and filing trends" },
  { id: "analyst", name: "Analyst Reports", icon: "🏦", persona: "a premium industry analyst desk — forecasts, ratings, and competitive analysis" },
  { id: "expert", name: "Expert Network", icon: "🧠", persona: "an expert-network transcript service — primary insight from practitioner interviews" },
];

const byId = (id: string) => SOURCES.find((s) => s.id === id);

export type ResearchEvent =
  | { type: "status"; text: string }
  | { type: "narration"; text: string }
  | { type: "llm_active"; engine: string; turn: number }
  | { type: "provider_switch"; text: string }
  | { type: "purchase_attempt"; source: string; label: string; icon: string; reason: string }
  | { type: "purchase_ok"; source: string; label: string; hash: string }
  | { type: "purchase_blocked"; source: string; label: string; reason: string }
  | { type: "source_data"; source: string; label: string; text: string }
  | { type: "final"; text: string }
  | { type: "error"; message: string }
  | { type: "done"; spent: number };

export type RunArgs = {
  question: string;
  inputs: CreateIntentMandateInput;
  agentSecret: string;
};

const SYSTEM = `You are an autonomous research agent. You answer the user's question by purchasing premium data sources and synthesising what you find.

Each source costs ${SOURCE_PRICE} XLM. Every purchase is a REAL payment settled on the Stellar blockchain through a smart contract (MandateRegistry) that enforces a fixed budget set by your owner. You do not control the budget — if you try to spend past it, the contract REJECTS the payment and the source stays locked. You cannot override this.

Work like a real analyst on a budget:
- Decide which sources are most relevant to the question, then buy them with the purchase_source tool. You may request several in one turn.
- Buy your highest-value sources first — you may not be able to afford them all.
- If a purchase is rejected on-chain, do not retry it. Work with what you have.
- Before each purchase, give a one-line note on what you're about to do. Keep it short.

When you have gathered what your budget allows, write a final answer: a concise, well-structured synthesis (a few short paragraphs or bullets) that draws on the sources you successfully purchased and notes any limits from sources you could not afford.`;

/** A short, query-specific finding from one source, generated by a fast sub-agent
 *  role-playing that source. Falls back to a static summary if every provider fails. */
async function sourceFindings(llm: FailoverLlm, source: Source, question: string): Promise<string> {
  const fallback = `Access granted. ${source.name} would return ${source.persona}. (Live findings unavailable — using a cached summary.)`;
  try {
    const { response } = await llm.complete(
      {
        system: `You are ${source.persona}. A research agent has paid to query you. Return 3–5 concrete, realistic findings (data points, figures, facts, or insights) relevant to its question, in your domain's voice. Be specific and genuinely useful. No preamble, no caveats — just the findings as short bullet lines.`,
        messages: [{ role: "user", text: question }],
        maxTokens: 400,
      },
      "sub",
    );
    return response.text.trim() || fallback;
  } catch {
    return fallback;
  }
}

const blockReason = (msg: string): string =>
  msg.includes("#6") ? "budget exceeded" : msg.includes("#5") ? "mandate revoked" : msg.includes("#4") ? "mandate expired" : "rejected on-chain";

/** Last-resort synthesis when BOTH LLM providers are exhausted mid-run: assemble a
 *  real, clearly-labeled report from the sources already purchased on-chain so the
 *  run never ends on a blank screen. */
function degradedReport(question: string, collected: { label: string; text: string }[]): string {
  if (collected.length === 0) {
    return `**LLM providers are temporarily unavailable**, so a full synthesis could not be generated for:\n\n> ${question}\n\nNo sources were purchased on-chain. Please retry in a moment.`;
  }
  const body = collected.map((c) => `### ${c.label}\n${c.text}`).join("\n\n");
  return `_Assembled in degraded mode — both LLM providers were temporarily unavailable, so this report is compiled directly from the ${collected.length} source(s) the agent purchased on-chain._\n\n## Question\n${question}\n\n${body}`;
}

/** Drive the agent. Yields events as work happens; payments are sequential
 *  (the mandate sequence increments on-chain, so they must not run in parallel). */
export async function* runResearch({ question, inputs, agentSecret }: RunArgs): AsyncGenerator<ResearchEvent> {
  const llm = buildFailoverLlm(); // reads ANTHROPIC_API_KEY / OPENAI_API_KEY from the environment

  const tools: LlmTool[] = [
    {
      name: "purchase_source",
      description:
        "Pay 1 XLM on-chain to unlock one premium data source for this research task. Settles a real Stellar payment through the MandateRegistry contract, which enforces your budget. If you have spent your budget the payment is REJECTED and the source stays locked — so spend on your most valuable sources first.",
      inputSchema: {
        type: "object",
        properties: {
          source: { type: "string", enum: SOURCES.map((s) => s.id), description: "Which source to buy." },
          reason: { type: "string", description: "One short sentence: why this source is worth buying for the question." },
        },
        required: ["source", "reason"],
      },
    },
  ];

  const messages: LlmMessage[] = [{ role: "user", text: `Research question: ${question}` }];
  const collected: { label: string; text: string }[] = [];
  let spent = 0;

  log.info("research agent online", { question: question.slice(0, 56) });
  yield { type: "status", text: "Agent planning its research…" };

  for (let turn = 0; turn < 8; turn++) {
    log.step("agent reasoning", { turn: turn + 1 });

    let result;
    try {
      result = await llm.complete({ system: SYSTEM, messages, tools, maxTokens: 2000 }, "main");
    } catch (e) {
      if (e instanceof AllProvidersExhausted) {
        log.warn("all LLM providers exhausted — emitting degraded report", { sources: collected.length });
        yield { type: "final", text: degradedReport(question, collected) };
        break;
      }
      throw e;
    }

    // Surface any provider failover that happened on this call.
    for (const s of result.switches) {
      yield { type: "provider_switch", text: `${s.from} unavailable (${s.reason}) — switched to ${s.to}.` };
    }

    // Show which LLM the orchestrator picked for this turn.
    yield { type: "llm_active", engine: result.engine, turn: turn + 1 };
    log.info(`orchestrator selected ${result.engine} · turn ${turn + 1}`);

    const resp = result.response;
    messages.push({ role: "assistant", text: resp.text, toolCalls: resp.toolCalls });

    if (resp.text.trim()) {
      log.info("agent", { says: resp.text.trim().slice(0, 64) });
      yield { type: "narration", text: resp.text.trim() };
    }

    if (resp.stopReason !== "tool_calls") {
      yield { type: "final", text: resp.text.trim() };
      break;
    }

    const results: { toolCallId: string; content: string; isError?: boolean }[] = [];
    for (const tc of resp.toolCalls) {
      if (tc.name !== "purchase_source") {
        results.push({ toolCallId: tc.id, content: `Unknown tool "${tc.name}".`, isError: true });
        continue;
      }
      const input = tc.input as { source?: string; reason?: string };
      const src = byId(input.source ?? "");
      if (!src) {
        results.push({ toolCallId: tc.id, content: `Unknown source "${input.source}".`, isError: true });
        continue;
      }
      const reason = input.reason ?? "";
      log.step("agent wants a source", { source: src.name, reason: reason.slice(0, 48) });
      yield { type: "purchase_attempt", source: src.id, label: src.name, icon: src.icon, reason };
      try {
        const mandate = reapp.createIntentMandate(inputs); // same nonce, same on-chain id
        const hash = await reapp.agent({ mandate, signer: agentSecret }).pay(SOURCE_PRICE);
        spent += 1;
        yield { type: "purchase_ok", source: src.id, label: src.name, hash };
        log.step("fetching findings from source", { source: src.name });
        const data = await sourceFindings(llm, src, question);
        collected.push({ label: src.name, text: data });
        yield { type: "source_data", source: src.id, label: src.name, text: data };
        results.push({
          toolCallId: tc.id,
          content: `[${src.name}] purchase confirmed on-chain (tx ${hash.slice(0, 8)}…). Findings:\n${data}`,
        });
      } catch (e) {
        const why = blockReason(e instanceof Error ? e.message : String(e));
        yield { type: "purchase_blocked", source: src.id, label: src.name, reason: why };
        results.push({
          toolCallId: tc.id,
          content: `PAYMENT REJECTED ON-CHAIN (${why}). You cannot afford "${src.name}". Do not try to buy it again. If you have enough to answer, write your final answer now.`,
          isError: true,
        });
      }
    }
    messages.push({ role: "tool", results });
  }

  yield { type: "done", spent };
}
