/**
 * Server-side Research Agent: a real Claude agent (claude-opus-4-8) that pays,
 * on-chain, for the premium data sources it needs to answer a question.
 *
 * The agent is given a single `purchase_source` tool. Every call settles a REAL
 * Stellar payment through the published @reapp-sdk/core (MandateRegistry.execute_
 * payment). The mandate budget is enforced ON-CHAIN: once the agent has spent its
 * budget, the contract rejects further purchases and the agent must synthesise an
 * answer from what it could afford. The SDK is untrusted; the contract is the leash.
 *
 * Runs only in the Node API route. Streams structured events via an async generator.
 */
import Anthropic from "@anthropic-ai/sdk";
import { reapp, type CreateIntentMandateInput } from "@reapp-sdk/core";
import { log } from "./log";

/** Price per source, in XLM. The mandate budget (see reapp-server.BUDGET = "3.00")
 *  covers three of these — the contract blocks the fourth. */
export const SOURCE_PRICE = "1.00";

export type Source = {
  id: string;
  name: string;
  icon: string;
  /** First-person persona used when a sub-agent role-plays this source's findings. */
  persona: string;
};

export const SOURCES: Source[] = [
  { id: "market", name: "Market Data API", icon: "📈", persona: "a real-time financial market-data provider — prices, volume, liquidity, volatility, and on-chain flows" },
  { id: "academic", name: "Academic Papers", icon: "📚", persona: "a peer-reviewed academic research index — empirical studies, citations, and methodology" },
  { id: "news", name: "News Archive", icon: "📰", persona: "a global news and press-release archive — recent events, announcements, and market sentiment" },
  { id: "patents", name: "Patent Database", icon: "⚗️", persona: "a worldwide patent and IP-filings database — inventions, assignees, and filing trends" },
  { id: "analyst", name: "Analyst Reports", icon: "🏦", persona: "a premium industry analyst desk — forecasts, ratings, and competitive analysis" },
  { id: "expert", name: "Expert Network", icon: "🧠", persona: "an expert-network transcript service — primary insight from practitioner interviews" },
];

const byId = (id: string) => SOURCES.find((s) => s.id === id);

export type ResearchEvent =
  | { type: "status"; text: string }
  | { type: "narration"; text: string }
  | { type: "purchase_attempt"; source: string; label: string; icon: string; reason: string }
  | { type: "purchase_ok"; source: string; label: string; hash: string }
  | { type: "purchase_blocked"; source: string; label: string; reason: string }
  | { type: "source_data"; source: string; label: string; text: string }
  | { type: "final"; text: string }
  | { type: "error"; message: string }
  | { type: "done"; spent: number };

export type RunArgs = {
  question: string;
  inputs: CreateIntentMandateInput;
  agentSecret: string;
};

const SYSTEM = `You are an autonomous research agent. You answer the user's question by purchasing premium data sources and synthesising what you find.

Each source costs ${SOURCE_PRICE} XLM. Every purchase is a REAL payment settled on the Stellar blockchain through a smart contract (MandateRegistry) that enforces a fixed budget set by your owner. You do not control the budget — if you try to spend past it, the contract REJECTS the payment and the source stays locked. You cannot override this.

Work like a real analyst on a budget:
- Decide which sources are most relevant to the question, then buy them with the purchase_source tool. You may request several in one turn.
- Buy your highest-value sources first — you may not be able to afford them all.
- If a purchase is rejected on-chain, do not retry it. Work with what you have.
- Before each purchase, give a one-line note on what you're about to do. Keep it short.

When you have gathered what your budget allows, write a final answer: a concise, well-structured synthesis (a few short paragraphs or bullets) that draws on the sources you successfully purchased and notes any limits from sources you could not afford.`;

/** A short, query-specific finding from one source, generated by a fast sub-agent
 *  role-playing that source. Falls back to a static summary if the call fails. */
async function sourceFindings(client: Anthropic, source: Source, question: string): Promise<string> {
  const fallback = `Access granted. ${source.name} would return ${source.persona}. (Live findings unavailable — using a cached summary.)`;
  try {
    const r = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 400,
      thinking: { type: "disabled" },
      system: `You are ${source.persona}. A research agent has paid to query you. Return 3–5 concrete, realistic findings (data points, figures, facts, or insights) relevant to its question, in your domain's voice. Be specific and genuinely useful. No preamble, no caveats — just the findings as short bullet lines.`,
      messages: [{ role: "user", content: question }],
    });
    const text = r.content
      .filter((b): b is Anthropic.TextBlock => b.type === "text")
      .map((b) => b.text)
      .join("\n")
      .trim();
    return text || fallback;
  } catch {
    return fallback;
  }
}

const blockReason = (msg: string): string =>
  msg.includes("#6") ? "budget exceeded" : msg.includes("#5") ? "mandate revoked" : msg.includes("#4") ? "mandate expired" : "rejected on-chain";

/** Drive the agent. Yields events as work happens; payments are sequential
 *  (the mandate sequence increments on-chain, so they must not run in parallel). */
export async function* runResearch({ question, inputs, agentSecret }: RunArgs): AsyncGenerator<ResearchEvent> {
  const client = new Anthropic(); // reads ANTHROPIC_API_KEY from the environment

  const tools: Anthropic.Tool[] = [
    {
      name: "purchase_source",
      description:
        "Pay 1 XLM on-chain to unlock one premium data source for this research task. Settles a real Stellar payment through the MandateRegistry contract, which enforces your budget. If you have spent your budget the payment is REJECTED and the source stays locked — so spend on your most valuable sources first.",
      input_schema: {
        type: "object",
        properties: {
          source: { type: "string", enum: SOURCES.map((s) => s.id), description: "Which source to buy." },
          reason: { type: "string", description: "One short sentence: why this source is worth buying for the question." },
        },
        required: ["source", "reason"],
      },
    },
  ];

  const messages: Anthropic.MessageParam[] = [{ role: "user", content: `Research question: ${question}` }];
  let spent = 0;

  log.info("research agent online", { model: "claude-opus-4-8", question: question.slice(0, 56) });
  yield { type: "status", text: "Agent planning its research…" };

  for (let turn = 0; turn < 8; turn++) {
    log.step("agent reasoning", { turn: turn + 1 });
    const resp = await client.messages.create({
      model: "claude-opus-4-8",
      max_tokens: 2000,
      thinking: { type: "disabled" },
      system: SYSTEM,
      tools,
      messages,
    });
    messages.push({ role: "assistant", content: resp.content });

    for (const b of resp.content) {
      if (b.type === "text" && b.text.trim()) {
        log.info("agent", { says: b.text.trim().slice(0, 64) });
        yield { type: "narration", text: b.text.trim() };
      }
    }

    if (resp.stop_reason !== "tool_use") {
      const finalText = resp.content
        .filter((b): b is Anthropic.TextBlock => b.type === "text")
        .map((b) => b.text)
        .join("\n")
        .trim();
      yield { type: "final", text: finalText };
      break;
    }

    const toolResults: Anthropic.ToolResultBlockParam[] = [];
    for (const b of resp.content) {
      if (b.type !== "tool_use") continue;
      const input = b.input as { source: string; reason: string };
      const src = byId(input.source);
      if (!src) {
        toolResults.push({ type: "tool_result", tool_use_id: b.id, is_error: true, content: `Unknown source "${input.source}".` });
        continue;
      }
      log.step("agent wants a source", { source: src.name, reason: input.reason.slice(0, 48) });
      yield { type: "purchase_attempt", source: src.id, label: src.name, icon: src.icon, reason: input.reason };
      try {
        const mandate = reapp.createIntentMandate(inputs); // same nonce, same on-chain id
        const hash = await reapp.agent({ mandate, signer: agentSecret }).pay(SOURCE_PRICE);
        spent += 1;
        yield { type: "purchase_ok", source: src.id, label: src.name, hash };
        log.step("fetching findings from source", { source: src.name });
        const data = await sourceFindings(client, src, question);
        yield { type: "source_data", source: src.id, label: src.name, text: data };
        toolResults.push({
          type: "tool_result",
          tool_use_id: b.id,
          content: `[${src.name}] purchase confirmed on-chain (tx ${hash.slice(0, 8)}…). Findings:\n${data}`,
        });
      } catch (e) {
        const reason = blockReason(e instanceof Error ? e.message : String(e));
        yield { type: "purchase_blocked", source: src.id, label: src.name, reason };
        toolResults.push({
          type: "tool_result",
          tool_use_id: b.id,
          is_error: true,
          content: `PAYMENT REJECTED ON-CHAIN (${reason}). You cannot afford "${src.name}". Do not try to buy it again. If you have enough to answer, write your final answer now.`,
        });
      }
    }
    messages.push({ role: "user", content: toolResults });
  }

  yield { type: "done", spent };
}
